{
  "hash": "bc6904459cc24cf93fa46c4ad1dbc69c",
  "result": {
    "markdown": "---\ntitle: 'DATA429 HW7'\noutput:\n  pdf_document:\n    toc: true\n    toc_depth: '5'\n  html_document:\n    toc: true\n    collapsed: false\n    toc_float: true\n    toc_depth: 5\n---\n\n\n## Problem 1\n\nIn the previous example from Class 7B the SRS, not all departments were represented. The following data are from a stratified sample using academic division. The total number of faculty in Biological Sciences is 102, Physical Science is 310, Social Sciences is 217, and Humanities is 178 in the population.\n\nWhat is the proportion with no refereed publications?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(tidyverse)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\n── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──\n✔ dplyr     1.1.4     ✔ readr     2.1.5\n✔ forcats   1.0.0     ✔ stringr   1.5.1\n✔ ggplot2   3.5.1     ✔ tibble    3.2.1\n✔ lubridate 1.9.3     ✔ tidyr     1.3.1\n✔ purrr     1.0.2     \n── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──\n✖ dplyr::filter() masks stats::filter()\n✖ dplyr::lag()    masks stats::lag()\nℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors\n```\n:::\n\n```{.r .cell-code}\npubStr<-read.csv(\"https://raw.githubusercontent.com/kitadasmalley/Teaching/refs/heads/main/DATA429_599/CODE/pubStrat.csv\", \n                 header=TRUE)\n\nhead(pubStr)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n  Publications Biological Physical Social Humanities\n1            0          1       10      9          8\n2            1          2        2      0          2\n3            2          0        0      1          0\n4            3          1        1      0          1\n5            4          0        2      2          0\n6            5          2        1      0          0\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n### BIOLOGICAL\nn1<-sum(pubStr$Biological)\nphat1<-pubStr$Biological[1]/n1\n\n### PHYSICAL\nn2<-sum(pubStr$Physical)\nphat2<-pubStr$Physical[1]/n2\n\n### SOCIAL\nn3<-sum(pubStr$Social)\nphat3 = pubStr$Social[1]/n3\n\n### HUMANITIES\nn4<-sum(pubStr$Humanities)\nphat4 = pubStr$Humanities[1]/n4\n```\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\n### COMBINE\nN=807\nNh=c(102,310,217,178)\nnh = c(n1,n2,n3,n4)\n\nphats = c(phat1, phat2, phat3, phat4)\n\n## P HAT STRAT\np_hat_strat = sum((Nh/N) * phats)\np_hat_strat\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5668087\n```\n:::\n\n```{.r .cell-code}\n## STD ERR\nvar_phat_strat = sum((1-(nh/Nh))*((Nh/N)^2)*((phats*(1-phats))/(nh-1)))\n                \nstdErr_phat_strat = sqrt(var_phat_strat)\nstdErr_phat_strat\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.06583449\n```\n:::\n\n```{.r .cell-code}\n## CONF INT -> 90%\nconf = p_hat_strat+c(-1,1)*qnorm(.95)*sqrt(var_phat_strat)\nconf\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.4585206 0.6750968\n```\n:::\n:::\n\n\n#### Answer to Problem 1\n\nThe proportion of faculty with no refereed publications is 0.5666 or 56.6%. The standard error is 0.0658. The confidence interval is 0.4583, 0.6749\n\n## PROBLEM 2\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#### PUBLIC HEALTH\nph<-read.csv(\"https://raw.githubusercontent.com/kitadasmalley/Teaching/refs/heads/main/DATA429_599/CODE/healthjournals.csv\", \n             header=TRUE)\n\nstr(ph)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n'data.frame':\t198 obs. of  7 variables:\n $ Journal   : chr  \"AJPH\" \"AJPH\" \"AJPH\" \"AJPH\" ...\n $ NumAuthors: int  4 9 6 5 7 4 3 4 2 4 ...\n $ RandomSel : chr  \"No\" \"No\" \"No\" \"No\" ...\n $ RandomAssn: chr  \"No\" \"No\" \"No\" \"No\" ...\n $ ConfInt   : chr  \"Yes\" \"Yes\" \"Yes\" \"Yes\" ...\n $ HypTest   : chr  \"No\" \"Yes\" \"Yes\" \"Yes\" ...\n $ Asterisks : chr  \"No\" \"No\" \"No\" \"No\" ...\n```\n:::\n:::\n\n\n#### Part A - Sampling Weight\n\n\n::: {.cell}\n\n```{.r .cell-code}\nNh = c(280,103,164)\n\nnh = c(100,38,60)\nN = sum(Nh)\n\nsamp_weights = Nh/nh\nsamp_weights\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 2.800000 2.710526 2.733333\n```\n:::\n:::\n\n\nThe sampling weight for each stratum is:\n\nAmerican Journal of Public Health: 2.8\n\nAmerican Journal of Preventive Medicine: 2.711\n\nPreventive Medicine: 2.733\n\nThe sample design used proportional allocation.\n\n#### Part B - Percentage of articles that used things\n\n##### Only Confidence Intervals\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#TOTAL ESTIMATE\nph01 = ph %>% mutate(confint01 = (ConfInt == \"Yes\")) %>% group_by (Journal) %>%\n  summarize(p_hat01=mean(confint01, na.rm=TRUE),\n            nh=n())\nph01\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 3\n  Journal p_hat01    nh\n  <chr>     <dbl> <int>\n1 AJPH      0.76    100\n2 AJPM      0.474    38\n3 PM        0.8      60\n```\n:::\n\n```{.r .cell-code}\nconfinest = sum((Nh/N)*ph01$p_hat01)\n#0.71808\n\n#CI for hypothesis test \n#VAR\nphat_var_strat = sum(((Nh/N)^2)*(1-(nh/Nh))*((ph01$p_hat01*(1-ph01$p_hat01))/(nh-1)))\n\n#SE\nSE = sqrt(phat_var_strat)\nSE\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.0248133\n```\n:::\n\n```{.r .cell-code}\n#CI\nconff_int =confinest+c(-1,1)*qnorm(.975)*sqrt(phat_var_strat)\nconff_int\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.6694463 0.7667126\n```\n:::\n:::\n\n\nThe percentage of articles that used only CIs is 71.81%, with a 95% confidence interval from 66.9% to 76.7%.\n\n##### Only Hypothesis testing\n\n\n::: {.cell}\n\n```{.r .cell-code}\nph02 = ph %>% mutate(hypt01 = (HypTest == \"Yes\")) %>% group_by (Journal) %>%\n  summarize(p_h02=mean(hypt01, na.rm=TRUE),\n            nh=n())\nph02\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 3\n  Journal p_h02    nh\n  <chr>   <dbl> <int>\n1 AJPH    0.85    100\n2 AJPM    0.816    38\n3 PM      0.867    60\n```\n:::\n\n```{.r .cell-code}\nhypt_est = sum((Nh/N)*ph02$p_h02)\n#0.84856\n\n#CI for hypothesis test \n#VAR\nphat_var_strat = sum(((Nh/N)^2)*(1-(nh/Nh))*((ph02$p_h02*(1-ph02$p_h02))/(nh-1)))\n\n#SE\nse = sqrt(phat_var_strat)\n\n#CI\nhyp_int =hypt_est+c(-1,1)*qnorm(.975)*sqrt(phat_var_strat)\n```\n:::\n\n\nThe percentage of articles that used hypothesis tests only is 84.86%, with a 95% confidence interval from 80.84% to 88.87% of articles.\n\n##### Both confidence intervals and hypothesis testing\n\n\n::: {.cell}\n\n```{.r .cell-code}\nph03 = ph %>% mutate(cihyp = (HypTest == \"Yes\" & ConfInt == \"Yes\")) %>% group_by (Journal) %>%\n  summarize(p_h03=mean(cihyp, na.rm=TRUE),\n            nh=n())\nph03\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 3\n  Journal p_h03    nh\n  <chr>   <dbl> <int>\n1 AJPH    0.68    100\n2 AJPM    0.368    38\n3 PM      0.717    60\n```\n:::\n\n```{.r .cell-code}\nboth_est = sum((Nh/N)*ph03$p_h03)\n#0.6323\n\n#CI for hypothesis test \n#VAR\nphat_var_strat = sum(((Nh/N)^2)*(1-(nh/Nh))*((ph03$p_h03*(1-ph03$p_h03))/(nh-1)))\n\n#SE\nse = sqrt(phat_var_strat)\n\n#CI\nboth_int =both_est+c(-1,1)*qnorm(.975)*sqrt(phat_var_strat)\nboth_int\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5802035 0.6844425\n```\n:::\n:::\n\n\nThe percentage of articles that used both Confidence Intervals and hypothesis testing is 63.23%, with a 95% confidence interval from 58.02% to 68.44%.\\\n\n##### Neither Confidence Intervals nor Hypothesis testing\n\n\n::: {.cell}\n\n```{.r .cell-code}\nph04 = ph %>% mutate(non = (HypTest == \"No\" & ConfInt == \"No\")) %>% group_by (Journal) %>%\n  summarize(p_h04=mean(non, na.rm=TRUE),\n            nh=n())\nph04\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 3\n  Journal  p_h04    nh\n  <chr>    <dbl> <int>\n1 AJPH    0.07     100\n2 AJPM    0.0789    38\n3 PM      0.05      60\n```\n:::\n\n```{.r .cell-code}\nnon_est = sum((Nh/N)*ph04$p_h04)\n#0.0657\n\n#CI for hypothesis test \n#VAR\nphat_var_strat = sum(((Nh/N)^2)*(1-(nh/Nh))*((ph04$p_h04*(1-ph04$p_h04))/(nh-1)))\n\n#SE\nse = sqrt(phat_var_strat)\n\n#CI\nnon_int =non_est+c(-1,1)*qnorm(.975)*sqrt(phat_var_strat)\nnon_int\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.03792664 0.09345025\n```\n:::\n:::\n\n\nThe percentage of articles that used neither Confidence Intervals nor hypothesis testing is 6.57%, with a 95% confidence interval from 3.79% to 9.35%.\n\n#### PART C\n\nGive a point estimate and 95% CI for the mean number of authors per article\n\n\n::: {.cell}\n\n```{.r .cell-code}\n#Y BARS\nph06 = ph %>% group_by (Journal) %>%\n  summarize(p_h06=mean(NumAuthors, na.rm=TRUE),vars=var(NumAuthors, na.rm=TRUE),\n            nh=n())\nph06\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 4\n  Journal p_h06  vars    nh\n  <chr>   <dbl> <dbl> <int>\n1 AJPH     4.88  5.40   100\n2 AJPM     5.58  7.17    38\n3 PM       6.3  14.5     60\n```\n:::\n\n```{.r .cell-code}\ny_bar_strat = sum((Nh/N) * ph06$p_h06)\ny_bar_strat\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 5.437352\n```\n:::\n\n```{.r .cell-code}\nn=sum(ph06$nh)\nvar_ybar_strat = sum((Nh/N)^2 * ((1-(nh/Nh))*(ph06$vars/nh)))\n\n#SE\nstdErr_ybar_strat = sqrt(var_ybar_strat)\n\n#CI\ny_bar_strat + c(-1,1)*qt(.975, 198-3)*stdErr_ybar_strat\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 5.112817 5.761887\n```\n:::\n:::\n\n\nThe point estimate is 5.437. The confidence interval is 5.113, 5.762 for both confidence interval and hypothesis tests. \n\n#### PART D\n\nEstimate the percentage and total number of articles (among the 547 in the population) that use neither random selection nor random assignment, along with 95% CIs.\n\n##### Percentage\n\n\n::: {.cell}\n\n```{.r .cell-code}\nph05 = ph %>% mutate(nont = (RandomSel == \"No\" & RandomAssn == \"No\")) %>% group_by (Journal) %>%\n  summarize(p_h05=mean(nont, na.rm=TRUE),\n            nh=n())\nph05\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n# A tibble: 3 × 3\n  Journal p_h05    nh\n  <chr>   <dbl> <int>\n1 AJPH    0.67    100\n2 AJPM    0.526    38\n3 PM      0.633    60\n```\n:::\n\n```{.r .cell-code}\nnont_est = sum((Nh/N)*ph05$p_h05)\n#0.63195\n\n#CI for hypothesis test \n#VAR\nphat_var_strat = sum(((Nh/N)^2)*(1-(nh/Nh))*((ph05$p_h05*(1-ph05$p_h05))/(nh-1)))\n\n#SE\nse = sqrt(phat_var_strat)\n\n#CI\nnont_int =nont_est+c(-1,1)*qnorm(.975)*sqrt(phat_var_strat)\nnont_int\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5782278 0.6856742\n```\n:::\n:::\n\n\nThe percentage of articles that used neither confidence intervals nor hypothesis testing is 63.195%, with a 95% confidence interval from 57.8% to 68.6%.\n\n##### Total\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntot_est = N*nont_est\n\n#CI\nphat_var_strat = sum(((Nh/N)^2)*(1-(nh/Nh))*((ph05$p_h05*(1-ph05$p_h05))/(nh-1)))\n\n\n#do both proportions and totals use qnorm? why?\ntot_int=tot_est+c(-1,1)*qnorm(.975)*sqrt(N^2*phat_var_strat)\ntot_int\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 316.2906 375.0638\n```\n:::\n:::\n\n\nThe estimated total number of articles that used neither confidence intervals nor hypothesis testing is 345 (result was 345.677), with a 95% confidence interval from 316 to 375.\n\n#### PART E\n\nDo the statistics calculated in this exercise describe all public health research articles? To what population do they apply?\n\n##### ANSWER: \n\nThe statistics in this exercise do not describe all public health research articles. They apply only to the scope in which the data was collected. While these statistics can provide insights, it’s likely not representative. ",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}