---
title: Experience
---

## Odyssey World International

I've had the privilege of working with Odyssey World International on their Community Asset Map project. On this mapping initiative, I review "listening sessions" to extract key insights and aggregated data on healthcare providers of color in Southwest WA and the Portland-Metro area to create a Community Asset Map, ensuring marginalized communities can access culturally competent care. 

To view the map, please visit this website: https://www.google.com/maps/d/u/0/edit?mid=1lxialY7veKVCIv3KtGDCmiVtoZ0jhdc&usp=sharing
To learn more about Odyssey World, please visit their website here: https://www.odysseyworld.org/

----

## Coursework

In my Survey Design and Sampling Methodology course I gained valuable skills that I've been able to apply to other Data Science positions. Over the semester I developed experience cleaning and visualizing PUMs and PUMA data, carefully designing surveys and sampling strategies to minimize bias, completed CITI/IRB training to expand piratical knowledge for handling sensitive date, and more! Through my coursework at Willamette, I have expanded my technical skill set in addition to the valuable relationship building skills necessary to work as a community to affect change.

----

## LGBTQ Center OC

During my time at the LGBTQ Center in Orange County CA, I researched policy related to mental health and restorative justice, designed data-driven presentations, and analyzed survey statistics to measure program success. Other projects I was assigned through this position involved restorative justice work, an educational social media campaign on the War on Drugs, and workshops on alcohol, tobacco & other drugs (ATOD). These experiences have strengthened my ability to interpret data for non-technical audiences—an essential skill for effectively communicating public opinion research findings.